# Generated by Django 4.2.1 on 2023-07-24 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('telephone_num', models.IntegerField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254)),
                ('avto', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('short_content', models.TextField(default='')),
                ('author_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog_deteiling.author')),
            ],
        ),
    ]
