# Generated by Django 4.2.1 on 2023-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0003_delete_image_feedback_image_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='my_data//%Y/%m/%d/'),
        ),
    ]
