# Generated by Django 4.2.1 on 2023-08-09 17:57

import blog_deteiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0004_alter_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog_deteiling.models.get_file_path),
        ),
    ]
