# Generated by Django 4.2.1 on 2023-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0009_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(default='', max_length=40)),
                ('address', models.CharField(default='', max_length=40)),
                ('work_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
