# Generated by Django 4.2.1 on 2023-08-11 13:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0011_alter_contacts_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='tel_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
