# Generated by Django 4.2.1 on 2023-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0013_indexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
