# Generated by Django 4.2.1 on 2023-08-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0015_remove_post_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_info',
        ),
    ]
