# Generated by Django 4.2.1 on 2023-08-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_deteiling', '0018_alter_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='images',
            new_name='image',
        ),
    ]
